version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'weekly'
  - package-ecosystem: 'npm'
    directory: '/packages/tools/eslint-config'
    schedule:
      interval: 'weekly'
  - package-ecosystem: 'npm'
    directory: '/packages/tools/typescript'
    schedule:
      interval: 'weekly'
  - package-ecosystem: 'npm'
    directory: '/packages/tools/jest'
    schedule:
      interval: 'weekly'
  - package-ecosystem: 'npm'
    directory: '/packages/core/http'
    schedule:
      interval: 'weekly'
  - package-ecosystem: 'npm'
    directory: '/packages/core/router'
    schedule:
      interval: 'weekly'
  - package-ecosystem: 'npm'
    directory: '/packages/core/schema'
    schedule:
      interval: 'weekly'
  - package-ecosystem: 'npm'
    directory: '/packages/core/container'
    schedule:
      interval: 'weekly'
  - package-ecosystem: 'npm'
    directory: '/packages/core/logger'
    schedule:
      interval: 'weekly'
  - package-ecosystem: 'npm'
    directory: '/packages/core/server'
    schedule:
      interval: 'weekly'
  - package-ecosystem: 'npm'
    directory: '/packages/core/reflection'
    schedule:
      interval: 'weekly'
