version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'daily'
  - package-ecosystem: 'npm'
    directory: '/packages/tools/eslint-config'
    schedule:
      interval: 'daily'
  - package-ecosystem: 'npm'
    directory: '/packages/tools/typescript'
    schedule:
      interval: 'daily'
  - package-ecosystem: 'npm'
    directory: '/packages/tools/jest'
    schedule:
      interval: 'daily'
  - package-ecosystem: 'npm'
    directory: '/packages/core/http'
    schedule:
      interval: 'daily'
  - package-ecosystem: 'npm'
    directory: '/packages/core/router'
    schedule:
      interval: 'daily'
  - package-ecosystem: 'npm'
    directory: '/packages/core/schema'
    schedule:
      interval: 'daily'
