version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'daily'
  - package-ecosystem: 'npm'
    directory: '/packages/eslint-config'
    schedule:
      interval: 'daily'
  - package-ecosystem: 'npm'
    directory: '/packages/typescript'
    schedule:
      interval: 'daily'
  - package-ecosystem: 'npm'
    directory: '/packages/jest'
    schedule:
      interval: 'daily'
