name: Continues Integration
on: push
jobs:
  release:
    name: Continues Integration
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 'lts/*'
      - name: Install Yarn
        run: npm install -g yarn
      - name: Install NX
        run: npm install -g nx
      - name: Install dependencies
        run: yarn install --frozen-lockfile
      - name: Lint all
        run: nx run-many --target=lint --all
      - name: Test all
        run: nx run-many --target=test --all
      - name: Build all
        run: nx run-many --target=build --all
